apiVersion: v1
kind: Pod
metadata:
  name: bad-pod
  namespace: dev
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  containers:
    - name: bad-container
      image: ubuntu:22.04
      command: ["sleep", "3600"]
      securityContext:
        privileged: true
        runAsNonRoot: false
        runAsUser: 0
        allowPrivilegeEscalation: true
        capabilities:
          add: ["NET_ADMIN", "SYS_PTRACE"]  
      volumeMounts:
        - name: host-root
          mountPath: /host
  volumes:
    - name: host-root
      hostPath:
        path: /              
        type: Directory
