apiVersion: v1
kind: Pod
metadata:
  name: taint-test-yes
  namespace: dev
spec:
  nodeSelector:
    role: worker
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "lab"
    effect: "NoSchedule"
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.10
