apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      nodeSelector:
        GPU: "true"
      containers:
        - name: frigate
          image: ghcr.io/blakeblackshear/frigate:stable
          ports:
            - containerPort: 5000
              name: web
          env:
            - name: FRIGATE_DB_PATH
              value: /config/frigate.db
          volumeMounts:
            - name: config-storage
              mountPath: /config
      volumes:
        - name: config-storage
          persistentVolumeClaim:
            claimName: frigate-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: frigate
  namespace: dev
spec:
  selector:
    app: frigate
  ports:
    - name: http
      port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frigate
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
    - host: nvr.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frigate
                port:
                  number: 80
