apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
  namespace: dev
spec:
  containers:
    - name: test
      image: nginx:1.27
      command: ["sh", "-c", "echo 'USERNAME: '; cat /etc/secrets/USERNAME; echo 'PASSWORD: '; cat /etc/secrets/PASSWORD; sleep 3600"]
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: app-secret