apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
  namespace: dev
spec:
  containers:
    - name: test
      image: nginx:1.27
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: PASSWORD