apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-env-demo
  namespace: labs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: env-demo
  template:
    metadata:
      labels:
        app: env-demo
    spec:
      containers:
      - name: demo
        image: nginx:1.27
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret