apiVersion: v1
kind: Pod
metadata:
  name: with-toleration
spec:
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "demo"
    effect: "NoSchedule"
  containers:
  - name: app
    image: nginx