---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: warehouse-cv-secret
  namespace: warehouse-cv
spec:
  encryptedData:
    OBJECT_STORE_ACCESS_KEY: AgAD9syIx5DPoN6sdEouPCB3sDbXNiOs6aMAWVE1YeBjF3Bg6ti9X3ue5RfhqGig5sUEsxPeFHzqUpjERQ5BGbPmtveYqB42L1biGLIUB98TRItj5NBGdRoqd5kCO+QqgFguZI0+mvyb9lZ2QY4YXzqYdhQ5+oN/oo9nxZGlnXfb43rHr9Vezlpn2euU2fFs6dcFHu8gQ7rkkqNkUixX+VIbqFkPZiGDWP1s6982OyqI7z1GMNlZPXmxff19ZFZdze46ZQwClXaQ+8zucfP8vs1ZVh3Xlq7DnNrHJe6rEAqEtpU7ApnwfOo0vJg5Yjazt0v9rUaOm4okoPBNWnMvlKs8EzF/J5ZSdb+UCNYvqU26VnWVqqwm0JsXLLyuJr8LBkVruXc5uPRpF2kTOWA9gVKlzLeeYlHCaNxsoq/oKyF8A0P9ZeDFe3vhmxqvbe0l2yM6f6q+K0LszyTS2E732UTLc7dzMpEMTB3J1vN9y8vjfa5MjvvduRtV53MNYfv3eLgXE9ZhqN2MglkZfgNftsDr+2SV5wNfV53co5KdRQKDNHva/HnVjoNPsphtwOJ7ajWnWwf9noeP5h7HTRqCf0+TW1kXkyMY0smZkVIzJCJ1WhpSwKCe2mGfbSoNSDLfS+b+Lzvc6FSQz6ThWqL2dBhW729o4+DdZ2DhJXWRsEcG/OtRgq4Niz0I91dtdBtUTLjEl84y
    OBJECT_STORE_SECRET_KEY: AgCnoQefDZOFzfuqbprn6V+ugP5PelZfJa9piJd7b/7pLFUaoSjwduaRRyW79gzXllOdpbgQm3VMnrvmVIerAILz1TqPmH6V6K5BUMYYOjmKkBYzTBNN+UGrIlDsli1+H3eqCB6Uc6UziiuTZ3RZXFfv+ubdffvFCG2vtLkrfF1cuBv6bugUgfdvoJ7PubqPInmShApwsymSnXT3hfHWZPMs1V2sNSHJ6PgiTbr1QqOzPWJA8aMNTZKVCF6E+MUOijGiScp84yxF6rip5z0Nb1JE2e9EkGREnttCyftRMq/eRwIuPv/xMdaYhhg1sIMf8yOIc7OSVWo1hMQaz9j81AILxit4a4IiPopj4AWlDnX4kyMZKQIVl2ybgPLoAGayhjGf36Q1X91aOJ8K2LOjaLhodiluhaWFRuwg8Jdjtij64CrxYFk5cpQFVevu19+6muealNj3AF5Cns8JSvqzSiXIfexxhjHbfppLma87TegoQZGMIMB5yqewfDqr77ukQgpEAa3d4o/gQbrfHPdnOtjvvZF1xRWWp3QgQ5xNapX0bi8DQAPjrASWTRT7y8XcKD0HPw1m+/VzzxYuF1qHauT+I6ly2o8BYmkP42IIejPXNi/HqaVbp0Too/UAi5ssAUI1smXuqxQRajDtP2YOSrLQ8LlCYkWi6PZPJMriaS+UYHmvNanjpA80g2tDqnMLr1yQAbYyew==
  template:
    metadata:
      name: warehouse-cv-secret
      namespace: warehouse-cv
