apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagepullback-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagepullback-demo
  template:
    metadata:
      labels:
        app: imagepullback-demo
    spec:
      containers:
      - name: app
        image: nginx
