apiVersion: v1
kind: Pod
metadata:
  name: restricted-pod
  namespace: dev
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 2000
  containers:
  - name: secure-container
    image: nginx
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      capabilities:
        drop:
        - ALL
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "100m"
        memory: "64Mi"